# Generated by Django 3.1 on 2020-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='user ID')),
                ('name', models.TextField(verbose_name='username')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
