# Generated by Django 3.1 on 2020-08-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Messages'},
        ),
    ]
